import { query } from "./_generated/server";
import { v } from "convex/values";

export const getAllScooters = query({
  args: {},
  handler: async () => {
    return [
      {
        id: "elk-rover",
        name: "Elk Rover",
        wheels: 2,
        power: "2000W",
        maxSpeed: "25 MPH",
        range: "20 mi",
        tire: "Normal fat",
        price: 1299.99,
        originalPrice: null,
        badges: ["Cheapest", "Beginner Friendly"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/7effa899-7bab-4f0c-9bc2-ad79713126bd",
        rating: 4.8,
        reviews: 127,
        inStock: true,
      },
      {
        id: "elk-velocity",
        name: "Elk Velocity",
        wheels: 2,
        power: "3000W",
        maxSpeed: "35 MPH",
        range: "30 mi",
        tire: "Normal fat",
        price: 1499.99,
        originalPrice: 1749.99,
        badges: ["Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/27cb123f-acb4-4a46-8c38-0cf7e7a196d9",
        rating: 4.9,
        reviews: 203,
        inStock: true,
      },
      {
        id: "elk-cruiser",
        name: "Elk Cruiser",
        wheels: 2,
        power: "3000W",
        maxSpeed: "35 MPH",
        range: "30 mi",
        tire: "Normal fat",
        price: 1849.99,
        originalPrice: 1999.99,
        badges: ["Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/e11dfd25-daaf-488e-9070-5a5fc7ca7a3d",
        rating: 4.9,
        reviews: 312,
        inStock: true,
      },
      {
        id: "elk-jubilee",
        name: "Elk Jubilee",
        wheels: 3,
        power: "3000W",
        maxSpeed: "25 MPH",
        range: "30 mi",
        tire: "Normal fat",
        price: 2199.99,
        originalPrice: null,
        badges: [],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/213096d9-08dd-48ca-9b06-836331c5531e",
        rating: 4.7,
        reviews: 89,
        inStock: true,
      },
      {
        id: "elk-jubilee-x",
        name: "Elk Jubilee X",
        wheels: 3,
        power: "3000W",
        maxSpeed: "25 MPH",
        range: "20 mi",
        tire: "Off-road fat",
        price: 2499.99,
        originalPrice: 2749.99,
        badges: ["Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/90c56e58-647e-430d-980a-a15415c694db",
        rating: 4.9,
        reviews: 156,
        inStock: true,
      },
      {
        id: "elk-patriot",
        name: "Elk Patriot",
        wheels: 3,
        power: "6000W",
        maxSpeed: "34 MPH",
        range: "30 mi",
        tire: "Off-road fat",
        price: 2749.99,
        originalPrice: 2999.99,
        badges: ["Most Powerful", "Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/97e86591-ca46-4808-aac3-d157888a6d6f",
        rating: 5.0,
        reviews: 241,
        inStock: false,
      },
      {
        id: "elk-thunderbolt",
        name: "Elk ThunderBolt",
        wheels: 2,
        power: "4000W",
        maxSpeed: "45 MPH",
        range: "30 mi",
        tire: "Off-road fat",
        price: 2299.99,
        originalPrice: 2549.99,
        badges: ["Fastest", "Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/c8f61d9e-3dad-4ee9-8ced-7b99e8521cbc",
        rating: 4.9,
        reviews: 178,
        inStock: true,
      },
    ];
  },
});

export const getScootersByCategory = query({
  args: { wheels: v.optional(v.number()) },
  handler: async (_ctx, args) => {
    const allScooters = [
      {
        id: "elk-rover",
        name: "Elk Rover",
        wheels: 2,
        power: "2000W",
        maxSpeed: "25 MPH",
        range: "20 mi",
        tire: "Normal fat",
        price: 1299.99,
        originalPrice: null,
        badges: ["Cheapest", "Beginner Friendly"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/7effa899-7bab-4f0c-9bc2-ad79713126bd",
        rating: 4.8,
        reviews: 127,
        inStock: true,
      },
      {
        id: "elk-velocity",
        name: "Elk Velocity",
        wheels: 2,
        power: "3000W",
        maxSpeed: "35 MPH",
        range: "30 mi",
        tire: "Normal fat",
        price: 1499.99,
        originalPrice: 1749.99,
        badges: ["Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/27cb123f-acb4-4a46-8c38-0cf7e7a196d9",
        rating: 4.9,
        reviews: 203,
        inStock: true,
      },
      {
        id: "elk-cruiser",
        name: "Elk Cruiser",
        wheels: 2,
        power: "3000W",
        maxSpeed: "35 MPH",
        range: "30 mi",
        tire: "Normal fat",
        price: 1849.99,
        originalPrice: 1999.99,
        badges: ["Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/e11dfd25-daaf-488e-9070-5a5fc7ca7a3d",
        rating: 4.9,
        reviews: 312,
        inStock: true,
      },
      {
        id: "elk-jubilee",
        name: "Elk Jubilee",
        wheels: 3,
        power: "3000W",
        maxSpeed: "25 MPH",
        range: "30 mi",
        tire: "Normal fat",
        price: 2199.99,
        originalPrice: null,
        badges: [],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/213096d9-08dd-48ca-9b06-836331c5531e",
        rating: 4.7,
        reviews: 89,
        inStock: true,
      },
      {
        id: "elk-jubilee-x",
        name: "Elk Jubilee X",
        wheels: 3,
        power: "3000W",
        maxSpeed: "25 MPH",
        range: "20 mi",
        tire: "Off-road fat",
        price: 2499.99,
        originalPrice: 2749.99,
        badges: ["Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/90c56e58-647e-430d-980a-a15415c694db",
        rating: 4.9,
        reviews: 156,
        inStock: true,
      },
      {
        id: "elk-patriot",
        name: "Elk Patriot",
        wheels: 3,
        power: "6000W",
        maxSpeed: "34 MPH",
        range: "30 mi",
        tire: "Off-road fat",
        price: 2749.99,
        originalPrice: 2999.99,
        badges: ["Most Powerful", "Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/97e86591-ca46-4808-aac3-d157888a6d6f",
        rating: 5.0,
        reviews: 241,
        inStock: false,
      },
      {
        id: "elk-thunderbolt",
        name: "Elk ThunderBolt",
        wheels: 2,
        power: "4000W",
        maxSpeed: "45 MPH",
        range: "30 mi",
        tire: "Off-road fat",
        price: 2299.99,
        originalPrice: 2549.99,
        badges: ["Fastest", "Fall Sale"],
        image: "https://harmless-tapir-303.convex.cloud/api/storage/c8f61d9e-3dad-4ee9-8ced-7b99e8521cbc",
        rating: 4.9,
        reviews: 178,
        inStock: true,
      },
    ];

    if (args.wheels !== undefined) {
      return allScooters.filter((s) => s.wheels === args.wheels);
    }

    return allScooters;
  },
});